version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 run:app
    volumes:
      - static_volume:/root/CloudExp/CloudExp/static
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudexp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3300:3306

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/root/CloudExp/CloudExp/static
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  db_data:
  static_volume: