version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:5000
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudexp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3300:3306

volumes:
  db_data: