"""Init

Revision ID: a6600994bf2f
Revises: 
Create Date: 2021-08-06 20:53:06.834023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6600994bf2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('name_language', sa.String(length=40), nullable=True),
    sa.Column('description_language', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id_language'),
    sa.UniqueConstraint('name_language')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('privilages', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parts',
    sa.Column('id_part', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('name_part', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id_language'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_part')
    )
    op.create_table('chapters',
    sa.Column('id_chapter', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('name_chapter', sa.String(length=50), nullable=False),
    sa.Column('text_chapter', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id_part'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_chapter')
    )
    op.create_table('seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id_chapter'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('name_task', sa.String(length=100), nullable=True),
    sa.Column('text_task', sa.String(length=1000), nullable=True),
    sa.Column('solution', sa.String(length=1000), nullable=True),
    sa.Column('hint', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id_chapter'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_task')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('seo')
    op.drop_table('chapters')
    op.drop_table('parts')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
